FROM golang:1.25-bookworm

RUN apt-get update \
	&& apt-get install -y --no-install-recommends graphviz ca-certificates \
	&& rm -rf /var/lib/apt/lists/*

RUN go install golang.org/x/perf/cmd/benchstat@latest

RUN apt-get update \
    && apt-get install -y --no-install-recommends sysstat \
    && rm -rf /var/lib/apt/lists/*
    
ENV PATH="/go/bin:${PATH}"
